export { default as Navbar } from "./Navbar";
export { default as Footer } from "./Footer";
export { default as Welcome } from "./Welcome";
export { default as NFTS } from "./NFTS";
export { default as About } from "./About.jsx";
export { default as Roadmap } from "./Roadmap";
export { default as Team } from "./Team.jsx";
export { default as JoinUsOnDiscord } from "./JoinUsOnDiscord";
export { default as Faq } from "./Faq";
